### PR TITLE
Some fixes to get the VAXstation 3100 working

### PR DESCRIPTION
**Pull request by Pacjunk**

### CODE REVIEW

**Comment by erichelgeson** [comment]
Thank you so much for the PR! I'll give it a test on a few machines I have.

**Comment by Pacjunk** [comment]
No problem. Unfortunately in my case the bluepill can't pull the lines down enough, so I have to run without one terminator. Seems to behave though...

My main code has other performance stuff and stripped some of the options, so has larger differences, so I re-applied the important changes to your current code base. It tests OK on my system. Most of the changes are due to modesense10 support and getting the drive geometry to report correctly. Also the #3F page code handling was an issue for my system. The Mac obviously doesn't care about these things.

**Comment by erichelgeson** [comment]
Tested in a Mac Plus
No performance difference from main
Saw additional/correct info in Silver Lining

I'll leave this in main for a week and ask for testers then cut a release. Thanks again!

**Comment by toncho11** [comment]
So can use BlueScsi on my Vax station 3100 ? Is it really working?

**Pull request merged**
